- name: Ensure needed packages are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl

- name: Check if oh-my-posh is already installed
  stat:
    path: /usr/local/bin/oh-my-posh-install
  register: installer

- name: Download script installation
  get_url:
    url: https://ohmyposh.dev/install.sh
    dest: /usr/local/bin/oh-my-posh-install
    mode: '0755'
  when: not installer.stat.exists

- name: Execute installation
  shell: /usr/local/bin/oh-my-posh-install
  changed_when: false
  when: not installer.stat.exists