- name: Ensure needed packages are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl

- name: Install Oh My Posh
  shell:
    cmd: |
      curl -s https://ohmyposh.dev/install.sh | bash -S
