- name: Ensure needed packages are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl

- name: Check if oh-my-posh is already installed
  stat:
    path: /usr/local/bin/oh-my-posh-install
  register: ohmyposhinstalled

- name: Download script installation
  get_url: https://ohmyposh.dev/install.sh
  target: /usr/local/bin/oh-my-posh-install
  when: not ohmyposhinstalled.stat.exists

- name: Execute installation
  shell: /usr/local/bin/oh-my-posh-install
  changed_when: false
  when: not ohmyposhinstalled.stat.exists